export const postCategories = [
  "animals",
  "architecture",
  "art",
  "automotive",
  "books",
  "business",
  "comedy",
  "culture",
  "design",
  "education",
  "entertainment",
  "environment",
  "fashion",
  "fitness",
  "food",
  "gadgets",
  "games",
  "general",
  "health",
  "history",
  "hobbies",
  "home",
  "inspiration",
  "language",
  "life",
  "lifestyle",
  "movies",
  "music",
  "nature",
  "news",
  "photography",
  "politics",
  "science",
  "sports",
  "technology",
  "travel",
  "work",
  "other",
] as const;

export const filteringOptions = ["title", "author", "tag"] as const;
